# Generated by Django 3.2.5 on 2021-07-31 16:31

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('automotive', 'Automotive, Auto Service'), ('accounting', 'Accounting, Finance'), ('banking', 'Banking, Lending'), ('call_center', 'Call Center, Customer Support'), ('cleaning', 'Cleaning, Household Services'), ('driving', 'Drivers, Couriers'), ('design', 'Design'), ('education', 'Education'), ('healthcare', 'Healthcare, Pharmacy'), ('it', 'Information Technology, Development'), ('legal', 'Legal'), ('management', 'Management'), ('media', 'Media, Publishing'), ('restaurants', 'Restaurants, Hotels, Bars'), ('security', 'Security')], max_length=15)),
                ('location', models.CharField(help_text='Write the city in english.', max_length=25)),
                ('type', multiselectfield.db.fields.MultiSelectField(choices=[('full_time', 'Full Time'), ('for_students', 'For Students'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('little_experience', 'Candidates with little or no experience'), ('part_time', 'Part Time')], max_length=71)),
                ('salary', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='jobs')),
            ],
        ),
    ]
