# Generated by Django 3.2.5 on 2021-08-01 13:40

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210801_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1920, 1080], upload_to='jobs'),
        ),
    ]
