# Generated by Django 3.2.5 on 2021-08-07 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_auth', '0008_alter_companyprofile_website'),
        ('jobs', '0007_alter_job_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivational_letter', models.TextField(max_length=800)),
                ('cv', models.FileField(upload_to='applications')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs_auth.applicantprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs_auth.companyprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
