# Generated by Django 3.2.5 on 2021-08-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='motivational_letter',
            field=models.TextField(max_length=2000),
        ),
    ]
