# Generated by Django 3.2.5 on 2021-08-09 20:03

import JobDiscover.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_application_motivational_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(upload_to='applications', validators=[JobDiscover.core.validators.validate_is_doc]),
        ),
    ]
