# Generated by Django 3.2.5 on 2021-08-04 17:51

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, help_text='Use image with 800x300px for best results.', keep_meta=True, null=True, quality=100, size=[800, 300], upload_to='jobs_auth/company_banners'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, help_text='Use image with 150x200px/300x400px for best results.', keep_meta=True, null=True, quality=100, size=[150, 200], upload_to='jobs_auth/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, help_text='Use image with 100x100px/200x200px for best results.', keep_meta=True, null=True, quality=100, size=[100, 100], upload_to='jobs_auth/company_icons'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
