# Generated by Django 3.2.5 on 2021-08-04 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_auth', '0003_alter_companyprofile_bulstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='bulstat',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(15)]),
        ),
    ]
