# Generated by Django 3.2.5 on 2021-08-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_auth', '0005_alter_companyprofile_bulstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='bulstat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
