# Generated by Django 3.2.5 on 2021-08-10 20:25

import JobDiscover.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_auth', '0009_alter_applicantprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='first_name',
            field=models.CharField(max_length=20, validators=[JobDiscover.core.validators.validate_start_with_capital]),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='last_name',
            field=models.CharField(max_length=20, validators=[JobDiscover.core.validators.validate_start_with_capital]),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='bulstat',
            field=models.IntegerField(blank=True, null=True, validators=[JobDiscover.core.validators.validate_correct_bulstat]),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
