# Generated by Django 3.2.5 on 2021-08-13 19:54

import JobDiscover.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_auth', '0010_auto_20210810_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='bulstat',
            field=models.BigIntegerField(blank=True, null=True, validators=[JobDiscover.core.validators.validate_correct_bulstat]),
        ),
    ]
